### ISSUE TITLE
Add CLI args processing

### ISSUE THREAD

**Issue by ndeoligence** [zero-to-mastery/ascii-art-2021#12]
The code currently always produces an ascii file when you run it. Which is not cool if you just want it printed out. In fact, there's no way to stop the file from being written to disk. And other will add more functionality soon.

We need a way to tell the program what to do when calling it. This is usually done using command-line arguments. (Like how you can call python like this: ```python -m venv /path/to/venv```

We need a way for our program to handle the same type of input. Something like: ```./community-version.py --image example/ztm-logo.png --output ztm-logo.txt```

That would tell it to open the ztm-logo.png and write the ascii to ztm-logo.txt. When run without --output, maybe it should just print to stdout

**Comment by Insidiae** [comment]
I took a shot to work on this issue and added some basic CLI args to `community-version.py`.

Right now it takes a `-i` or `--image` argument along with the file path to the input image, and an optional `-o` or `--outfile` argument specifying the output text file path, if any.

Running `python3 community-version.py -i .\example\ztm-logo.png` will produce the expected output of *only* writing the ASCII art into stdout.

Running `python3 community-version.py -i .\example\ztm-logo.png -o output.txt` writes the ASCII art into stdout, as well as writing the ASCII art into `output.txt`.
