### ISSUE TITLE
How can I help for this project?

### ISSUE THREAD

**Issue by Programmer-RD-AI** [zero-to-mastery/ascii-art-2021#56]
How can I help with this project?

I would recommend adding a project tab for this repo so we can see what is to do and what is currently doing and what is done.

I think it would be really easy for new contributors.

With best regards,
Ranuga

**Comment by ndeoligence** [comment]
thanks for the suggestion @Programmer-RD-AI 
I'll take a look at GH Projects. Hopefully it's an easy thing to manage and people will happily use it

we currently only have a few issues. And that's how one finds/suggests stuff to do. If it's not assigned to anyone, you can say you wanna do it and assign it to yourself.
