### ISSUE TITLE
Image path argument input is not being processed

### ISSUE THREAD

**Issue by juancwu** [zero-to-mastery/ascii-art-2021#70]
Whenever I run `python3 ./community_version.py -i image_path`, the program still ask for the image path. Inputting the path again does not resolve the problem. It hangs in there asking for a new input.
![Screen Shot 2021-10-20 at 11 00 35 PM](https://user-images.githubusercontent.com/46619361/138204034-70dfffd9-a092-4ea4-b801-aaa74a7aa05c.png)

Anyone know how to properly run the program?

**Comment by sachdevavaibhav** [comment]
@ndeoligence can I fix this issue?

**Comment by juancwu** [comment]
> @ndeoligence can I fix this issue?

Sorry, I didn't know you wanted to fix the issue. I already made a PR...

**Comment by sachdevavaibhav** [comment]
@juancwu 
No worries.🤝I am new to open source so I though it was a good issue to get started.
But now I just made another PR for catching error in save_img function.
